name: magic-wormhole
version: 0.1.0
synopsis: Interact with Magic Wormhole
description: |
  Honestly, who can say?
maintainer: Jonathan M. Lange <jml@mumak.net>
license: Apache
github: jml/haskell-magic-wormhole
category: Crypto

ghc-options: -Wall
default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - TypeApplications

dependencies:
  - base
  - protolude >= 0.2

library:
  source-dirs: src
  dependencies:
    - aeson
    - bytestring
    - containers
    - cryptonite
    - hashable
    - memory
    - network
    - network-uri
    - saltine
    - spake2 >= 0.4
    - stm
    - unordered-containers
    - websockets

executables:
  hocus-pocus:
    main: HocusPocus.hs
    source-dirs: cmd
    dependencies:
      - magic-wormhole
      - optparse-applicative
      - spake2 >= 0.4

tests:
  tasty:
    main: Tasty.hs
    source-dirs: tests
    dependencies:
      - aeson
      - bytestring
      - hedgehog
      - magic-wormhole
      - memory
      - process
      - saltine
      - spake2 >= 0.3
      - tasty
      - tasty-hedgehog
      - tasty-hspec

# These are only for tests.
data-files:
  - tests/python/derive_phase_key.py
  - tests/python/spake2_exchange.py
  - tests/python/version_exchange.py
