name: magic-wormhole
version: 0.1.0
synopsis: Interact with Magic Wormhole
description: |
  Honestly, who can say?
maintainer: Jonathan M. Lange <jml@mumak.net>
license: Apache
github: jml/haskell-magic-wormhole
category: Crypto

ghc-options: -Wall
default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - TypeApplications

dependencies:
  - base
  - protolude

library:
  source-dirs: src
  dependencies:
    - aeson
    - network
    - network-uri
    - websockets

executables:
  hocus-pocus:
    main: HocusPocus.hs
    source-dirs: cmd
    dependencies:
      - magic-wormhole
      - optparse-applicative

tests:
  tasty:
    main: Tasty.hs
    source-dirs: tests
    dependencies:
      - hedgehog
      - magic-wormhole
      - tasty
      - tasty-hedgehog
      - tasty-hspec

