name: magic-wormhole
version: 0.1.0
synopsis: Interact with Magic Wormhole
description: |
  Client library for interacting with a Magic Wormhole server.

  Magic Wormhole is a technology for getting things from one computer to another, safely.
  It does this by using a server to locate peers, and then using SPAKE2 encryption to
  negotiate a secure connection to a peer. It is especially useful for sending files
  and short messages to other humans.

  You can learn more about Magic Wormhole by exploring the documentation on
  the [canonical, Python
  implementation](https://github.com/warner/magic-wormhole).

maintainer: Jonathan M. Lange <jml@mumak.net>
license: Apache
github: LeastAuthority/haskell-magic-wormhole
category: Crypto
extra-source-files:
  - CHANGELOG.md

ghc-options: -Wall
default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - TypeApplications

dependencies:
  - base >= 4.9 && < 5
  - protolude >= 0.2
  - spake2 >= 0.4.1

library:
  source-dirs: src
  dependencies:
    - aeson
    - bytestring
    - containers
    - cryptonite
    - hashable
    - memory
    - network
    - network-uri
    - pqueue
    - saltine
    - stm
    - unordered-containers
    - websockets

executables:
  hocus-pocus:
    main: HocusPocus.hs
    source-dirs: cmd
    dependencies:
      - aeson
      - magic-wormhole
      - optparse-applicative
      - text

tests:
  tasty:
    main: Tasty.hs
    source-dirs: tests
    dependencies:
      - aeson
      - bytestring
      - hedgehog
      - magic-wormhole
      - memory
      - process
      - saltine
      - stm
      - tasty
      - tasty-hedgehog
      - tasty-hspec

# These are only for tests.
data-files:
  - tests/python/derive_phase_key.py
  - tests/python/nacl_exchange.py
  - tests/python/spake2_exchange.py
  - tests/python/version_exchange.py
