version: 2.1
jobs:
  build:
    docker:
      - image: debian/unstable-slim
    steps:
      - checkout
      - run:
          name: apt update
          command: apt update
      - run:
          name: Install libsodium (for saltine)
          command: apt install -y libsodium-dev
      - run:
          name: Install dependencies
          command: apt install -y cabal-install ghc
      - run:
          name: upgrade cabal
          command: |
             cabal update
             cabal install cabal-install
      - run:
          name: build the code
          command: |
             cabal configure
             cabal build
      - run:
          name: Install virtualenv
          command: apt install -y virtualenv
      - run:
          name: Setup Environment variable to not use Rust
          command: export CRYPTOGRAPHY_DONT_BUILD_RUST=1
      - run:
          name: Install Python build deps
          command: apt install -y gcc python-dev libssl-dev libffi-dev
      - run:
          name: Create virtualenv
          command: virtualenv --python=python3 testing-venv
      - run:
          name: enter into virtualenv and executing commands
          command: |
             source testing-venv/bin/activate
             echo "fetch get-pip to install pip"
             wget https://bootstrap.pypa.io/get-pip.py
             echo "Make pip executable"
             chmod +x ./get-pip.py
             echo "Install pip"
             ./get-pip.py
             echo "Install dependencies"
             pip install -r requirements.txt
             echo "run Tests"
             cabal test
