version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-13.22
    steps:
      - checkout
      - restore_cache:
          keys:
            - stack-ghc-{{ checksum "stack.yaml" }}
      - restore_cache:
          keys:
            - stack-deps-{{ checksum "package.yaml" }}
      - run:
          name: Set up Stack
          command: stack setup --no-terminal --no-reinstall
      - save_cache:
          key: stack-ghc-{{ checksum "stack.yaml" }}
          paths:
            - /root/.stack
      - run:
          # saltine needs libsodium 0.13+ and this is the only PPA I could find.
          name: Add PPA with libsodium 0.13+
          command: apt-add-repository -y ppa:ondrej/php
      - run:
          name: apt-get update
          command: apt-get update
      - run:
          name: Install libsodium (for saltine)
          command: apt-get install -y libsodium-dev
      - run:
          name: Install dependencies
          command: stack build --skip-ghc-check --no-terminal --test --only-dependencies
      - save_cache:
          key: stack-deps-{{ checksum "package.yaml" }}
          paths:
            - /root/.stack
            - .stack-work
      - run:
          name: Install virtualenv
          command: apt-get install -y python3-virtualenv
      - run:
          name: Install Python build deps
          command: apt-get install -y gcc python-dev libssl-dev libffi-dev
      - run:
          name: Create virtualenv
          command: virtualenv testing-venv
      - run:
          name: Install dependencies
          command: testing-venv/bin/pip install -r requirements.txt
      - run:
          name: Tests
          command: |
            . testing-venv/bin/activate
            stack test --skip-ghc-check --no-terminal magic-wormhole
